version: '3.1'
services:
  db:
    image: mysql
    container_name: db_clients
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - "3306:3306"
    volumes:
    - jazztech_data:/var/lib/mysql

volumes:
  jazztech_data: